### ISSUE TITLE
Missing instructions for `tests`

### ISSUE THREAD

**Issue by BenWinchester** [FraunhoferIWES/iwopy#11]
**Describe the bug**
The automated tests contained within the `tests` directory cannot be easily run, potentially due to a lack of clear documentation or possibly an issue around imports as is suggests in the tracebacks when trying to run these tests.

**To Reproduce**
- Running with `pytest`
  - In an environment _without_ `iwopy` installed _or_ in an environment _with_ `iwopy` installed
    ```bash
    (python-3-10-environment) user@machine:~/path/to/iwopy/repository$ python -m pytest tests
    ================================================================== test session starts 
    ==================================================================
    platform linux -- Python 3.10.10, pytest-7.4.0, pluggy-1.2.0
    rootdir: /home/bewinche/modelling/reviewing/iwopy
    collected 0 items / 7 errors                                                                                                                            
    ......
    ======================================================================== ERRORS =========================================================================
    ______________________________________________________ ERROR collecting tests/scipy/test_scipy.py 
    ImportError while importing test module '/home/bewinche/modelling/reviewing/iwopy/tests/scipy/test_scipy.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    ../../../anaconda3/envs/py310/lib/python3.10/importlib/__init__.py:126: in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    tests/scipy/test_scipy.py:3: in <module>
        from iwopy import DiscretizeRegGrid, SimpleConstraint
    iwopy/__init__.py:12: in <module>
        from . import interfaces
    iwopy/interfaces/__init__.py:2: in <module>
        from . import pymoo
    iwopy/interfaces/pymoo/__init__.py:1: in <module>
        from .optimizer import Optimizer_pymoo, DefaultCallback
    iwopy/interfaces/pymoo/optimizer.py:5: in <module>
        from .problem import SingleObjProblem, MultiObjProblem
    iwopy/interfaces/pymoo/problem.py:4: in <module>
        from .imports import check_import, Problem, Real, Integer
    E   ImportError: cannot import name 'Real' from 'iwopy.interfaces.pymoo.imports' (/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/pymoo/imports.py)
    ================================================================= short test summary info ================================================================
    ERROR tests/core/test_discr_grid.py
    ERROR tests/core/test_discretize.py
    ERROR tests/core/test_gradients_ana.py
    ERROR tests/core/test_varmap.py
    ERROR tests/pygmo/test_pygmo.py
    ERROR tests/pymoo/test_pymoo.py
    ERROR tests/scipy/test_scipy.py
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ==================================================================== 7 errors in 1.43s ===================================================================
      ```
- Running with Python directly
  - In an environment _without_ `iwopy` installed
    ```bash
    (python-3-10-without-iwopy) user@machine:~/path/to/iwopy/repository$ python tests/core/test_discr_grid.py 
    Traceback (most recent call last):
      File "/home/bewinche/modelling/reviewing/iwopy/tests/core/test_discr_grid.py", line 3, in <module>
        import iwopy
      File "/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/__init__.py", line 12, in <module>
        from . import interfaces
      File "/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/interfaces/__init__.py", line 2, in <module>
        from . import pymoo
      File "/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/interfaces/pymoo/__init__.py", line 1, in <module>
        from .optimizer import Optimizer_pymoo, DefaultCallback
      File "/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/interfaces/pymoo/optimizer.py", line 5, in <module>
        from .problem import SingleObjProblem, MultiObjProblem
      File "/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/interfaces/pymoo/problem.py", line 4, in <module>
        from .imports import check_import, Problem, Real, Integer
    ImportError: cannot import name 'Real' from 'iwopy.interfaces.pymoo.imports' (/home/bewinche/anaconda3/envs/py310/lib/python3.10/site-packages/iwopy/interfaces/pymoo/imports.py)
    ```
  - In an environment _with_ `iwopy` installed
    ```bash
    (python-3-10-with-iwopy) user@machine:~/path/to/iwopy/repository$ python tests/core/test_discr_grid.py 
    Traceback (most recent call last):
      File "/home/bewinche/modelling/reviewing/iwopy/tests/core/test_discr_grid.py", line 3, in <module>
        import iwopy
      File "/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/__init__.py", line 12, in <module>
        from . import interfaces
      File "/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/interfaces/__init__.py", line 2, in <module>
        from . import pymoo
      File "/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/interfaces/pymoo/__init__.py", line 1, in <module>
        from .optimizer import Optimizer_pymoo, DefaultCallback
      File "/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/interfaces/pymoo/optimizer.py", line 5, in <module>
        from .problem import SingleObjProblem, MultiObjProblem
      File "/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/interfaces/pymoo/problem.py", line 4, in <module>
        from .imports import check_import, Problem, Real, Integer
    ImportError: cannot import name 'Real' from 'iwopy.interfaces.pymoo.imports' (/home/bewinche/anaconda3/envs/testground/lib/python3.10/site-packages/iwopy/interfaces/pymoo/imports.py)
    ```

**Expected behavior**
From standard testing practices, a user would expect for the tests to be runnable, either with [`pytest`](https://docs.pytest.org/en/7.1.x/contents.html) or directly (e.g., `python path/to/test.py`). This should then produce a test output or some measure of success. It's possible that this issue is install related (e.g., that packages required for the testing do not come installed when installing `iwopy`as dependencies) or that documentation is missing and could be clearer around how to run these automated tests.

**Desktop (please complete the following information):**
 - OS: Debian 11.6

**Additional context**
This was raised as part of the review for the JOSS [here](https://github.com/openjournals/joss-reviews/issues/6014).

**Comment by SchmJo** [comment]
Thanks for the bug report. Which version of iwopy are you running? It this the latest main branch from github, or an installation from pypi, or from conda-forge? It seems that I cannot reproduce this behaviour in my local clone of the repository. Thanks

**Comment by SchmJo** [comment]
Sorry, I can now indeed reprodce this for a fresh install! I will try to find out what is behind this.

**Comment by SchmJo** [comment]
I think this due to `pymoo` not being installed. For me, `pip install pymoo` solved the issue (for conda installations please install from there). 

Currently the optimization packages are optional. However, this behaviour as it is now is not desired. I will think of a new solution.

**Comment by SchmJo** [comment]
@BenWinchester The instructions for tests have now been added to the [documentation](https://fraunhoferiwes.github.io/iwopy.docs/testing.html) and also the [README](https://github.com/FraunhoferIWES/iwopy?tab=readme-ov-file#testing).
